# Generated by Django 2.1.4 on 2018-12-05 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('signed', models.DateField(default=None)),
                ('deadline', models.DateField(default=None)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='contacts.Company')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider', to='contacts.Company')),
            ],
        ),
        migrations.CreateModel(
            name='DesignSituation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=30)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Contract')),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=30)),
                ('deadline', models.DateField()),
                ('design_situation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.DesignSituation')),
            ],
        ),
        migrations.AddField(
            model_name='revision',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='projects.Task'),
        ),
        migrations.AddField(
            model_name='designsituation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_situations', to='projects.Project'),
        ),
    ]
