# Generated by Django 2.1.4 on 2018-12-05 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='deadline',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='contract',
            name='signed',
            field=models.DateField(blank=True, default=None),
        ),
    ]
