# Generated by Django 2.1.4 on 2018-12-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='internal_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='internal_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
