# Generated by Django 2.1.4 on 2018-12-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20181215_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='deadline',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='signed',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
