# Generated by Django 2.1.4 on 2018-12-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20181218_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_id',
        ),
        migrations.AddField(
            model_name='task',
            name='internal_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
