# Generated by Django 2.1.4 on 2018-12-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20181218_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revision',
            name='revision_id',
        ),
        migrations.AddField(
            model_name='revision',
            name='internal_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
